### ISSUE TITLE
Does this work with search and replace :%s ?

### ISSUE THREAD

**Issue by process91** [haya14busa/incsearch.vim#107]
This works well for a typical search, but no highlighting when doing a search and replace, which would be quite useful. Is this a bug on my end, or is this not supported in this plugin?

**Comment by eshansingh** [comment]
That, as far as I know, is neither a built-in feature nor a feature of this plugin.

**Comment by haya14busa** [comment]
Sorry for the late reply. I don't have any plan to support highlighing for :substitute, because there is already the plugin to do that https://github.com/osyo-manga/vim-over

Please you vim-over.

Note that you can search first with incsearch.vim and then in :OverCommandLine, you can use previous searched pattern by `>%s//{string}/{flag}`

**Comment by sunaku** [comment]
On my Linux system, vim-over is significantly slower (takes 5 seconds for `OverCommandLine` to appear) than incsearch.vim (`/` prompt appears instantly). :bow: What is the secret behind vim-over's amazing speed? :neckbeard:
