### ISSUE TITLE
Can't paste?!

### ISSUE THREAD

**Issue by DelvarWorld** [haya14busa/incsearch.vim#35]
When I hit command-v (mac + macvim) in search mode it puts `"+gP`. What on earth?!

**Comment by jordwalke** [comment]
So it sounds like you found the solution. Will there be a fix?

**Comment by haya14busa** [comment]
@jordwalke

No, I didn't find good solution.

> So i guess <D-v> maps to "paste menu" (OSX system keyboard shortcut) and "paste menu" maps to "+gP

Since the system maps `<D-v>` to `"paste menu"` and it maps to `"+gP`, we cannot handle this from Vim script, I guess.

There are two solution.

### 1. workaround fix with IncSearchNoreMap

> `IncSearchNoreMap "+gP <C-r>+`

https://github.com/haya14busa/incsearch.vim/issues/35#issuecomment-67504976

### 2. Remap system keymap
https://github.com/haya14busa/incsearch.vim/issues/35#issuecomment-67508752

**Comment by jordwalke** [comment]
My suggestion was that you place `IncSearchNoreMap "+gP <C-r>+` as a mapping if the user is running MacVim.

**Comment by haya14busa** [comment]
Hmm... but there is a downside to map `IncSearchNoreMap "+gP <C-r>+ `. It cause waiting time for key a key code with typing `"`.

**Comment by jordwalke** [comment]
How much of a waiting time. I wasn't able to notice any additional time, though I'm usually very perceptive of additional interaction delays.

**Comment by jordwalke** [comment]
Oh, I just noticed that the delay is only in search mode. Yes, I definitely notice that. Is there a way control that delay amount only while in incsearch `/`?

**Comment by haya14busa** [comment]
I'm really sorry to late to reply.
The delay amount is same as `:h 'timeoutlen'`.

You can control it only while in incsearch with autocmd.

```vim
augroup incsearch-timeoutlen
  autocmd User IncSearchEnter :let g:save_timeoutlen = &timeoutlen | set timeoutlen=0
  autocmd User IncSearchLeave :let &timeoutlen = g:save_timeoutlen
augroup END
```

**Comment by jordwalke** [comment]
Okay, maybe that's good enough for an official solution in the repo? You could even guard it under an "if macvim" check.

**Comment by haya14busa** [comment]
I added the workaround mapping in dev branch. https://github.com/haya14busa/incsearch.vim/compare/dev

Could you please trying the dev branch? I cannot confirm the fix because I don't have mac.

For the `timeoutlen` issue, I don't want to manipulate it by default since it affects other key mappings too.

**Comment by haya14busa** [comment]
I guess it's closable. Please reopen if not.
