### ISSUE TITLE
Clear hlsearch on Insert

### ISSUE THREAD

**Issue by tscheffe** [haya14busa/incsearch.vim#80]
Love the plugin. Discovered the plugin in a few days ago and have been loving it. Missing one feature I'd like though, exiting hlsearch when pressing insert. In the same way
````viml
let g:insearch#auto_nohlsearch = 1
````
turns off hlsearch after cursor move.

Here is what I have in my `.vimrc` to achieve the desired effect.
````viml
augroup NoHlOnInsert
    au!

    " Exit hlsearch when entering insert as well
    autocmd InsertEnter * :set nohlsearch

    " Reenable it so that future searchs do hlsearch
    autocmd InsertLeave * :set hlsearch
augroup END
````

Question is three-fold:
- Is there a better way to do this? Is integrating with `incsearch.vim` for this sort of thing possible already? I looked through the help doc and tried a few of the `autocmd User` integration points but couldn't get it working. I feel like I'm stepping on toes doing it this way.
- Do you see potential in this as a feature for `insearch.vim`? I'm imaging something like `g:incsearch#auto_nohlsearch_on_insert` or something.
- If we arrive at a better way of doing it that integrates with `incsearch.vim` as is, does it warrant mention in the docs?

**Comment by haya14busa** [comment]
Thanks for the report @tscheffe

> Is there a better way to do this?

It should not manipulate user-defined option.

> Do you see potential in this as a feature for insearch.vim?

I also tried to clear highlight on insert enter but there are some problem, so I removed the feature in the past.
However, I implement it with saving user configuration getting inspired by your code :sparkles: Thanks :+1:

I merged this feature into dev branch https://github.com/haya14busa/incsearch.vim/tree/dev,
so could you please trying this branch?

**Comment by haya14busa** [comment]
Hi, @tscheffe

I'm sorry but I disable this feature which clear hlsearch on `InsertEnter` and instead,
I implemented another feature which clear highlight on `InsertLeave` and first `CursorMoved`.

The reason why I change this feature is

1. (implementation & convention) Modifying user-defined option, `&hlsearch`, is bad idea and I should avoid to do it as much as possible.
2. (usefulness) IMO, it's useful to retain highlight in insert mode because I can see highlight while editing target text by `cgn`
3. (implementation) I came up with a way to deal with `feedkeys()` in `Insert` mode in #82. So it's not necessary to turn off highlight on `InsertEnter` and remove `autocmd!` to call `feedkeys()`

So, I close this issue but thank you for the good request :sparkles:
